apiVersion: v1
kind: Service
metadata:
  name: simple-predict-front
spec:
  selector:
    app: simple-predict-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31234
  type: NodePort
  externalIPs:
    - 192.168.99.100
