apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: custom-prophet
spec:
  predictor:
    containers:
      - name: kserve-container
        image: konglsh96/kserve_practice:prophet
        resources:
          limits:
            cpu: 1
            memory: 500Mi
          requests:
            cpu: 1
            memory: 500Mi
