apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: custom-text-score
spec:
  predictor:
    containers:
      - name: kserve-container
        image: konglsh96/kserve_practice:textscore
        resources:
          limits:
            cpu: 1
            memory: 1000Mi
          requests:
            cpu: 1
            memory: 1000Mi
