apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: custom-prophet
  namespace: {{ .Values.namespace }}
spec:
  predictor:
    containers:
      - name: kserve-container
        image: konglsh96/simple-predict:prophet
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1
            memory: 500Mi
          requests:
            cpu: 1
            memory: 500Mi
