apiVersion: v1
kind: Service
metadata:
  name: simple-predict-front
spec:
  selector:
    app: simple-predict-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{ .Values.frontend.service.port }}
  type: NodePort
  externalIPs:
    - {{ .Values.frontend.service.ip }}

