apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: custom-text-score
  namespace: {{ .Values.namespace }}
spec:
  predictor:
    containers:
      - name: kserve-container
        image: konglsh96/simple-predict:textscore
        imagePullPolicy: Always
        resources:
          limits:
            cpu: {{ .Values.textscore.resources.limits.cpu }}
            memory: {{ .Values.textscore.resources.limits.memory }}
          requests:
            cpu: {{ .Values.textscore.resources.requests.cpu }}
            memory: {{ .Values.textscore.resources.requests.memory }}
